version: '3.7'
services:
  db:
    image: postgres
    container_name: postgrescontainer
    restart: always
    env_file:
      - .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    
  
  rabbitmq:
    build: rabbit/.
    container_name: rabbitmqcontainer
    ports:
      - 15672:15672
      - 5672:5672
    depends_on:
      - db

  tuumbackend:
    build: tuumBackend/.
    container_name: tuumbackendcontainer
    ports:
      - 8000:8080
    depends_on:
      - db
      - rabbitmq
  
  transactionconsumer:
    build: transactionsConsumer/.
    depends_on:
      - db
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
    
  accountconsumer:
    build: accountConsumer/.
    depends_on:
      - db
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
  next:
    container_name: next
    image: nextapp
    build:
      context: ./tuumfrontend
    ports:
      - 3000:3000
    depends_on:
      - db
      - rabbitmq
  
  nginxapp:
    container_name: nginx
    image: nginxapp:1.0.0
    build:
      dockerfile: nginx.dockerfile
    depends_on:
      - db
      - rabbitmq


    
  


  

  

